const ROUTE_PATH_MATCH_ALL = '*'
const ROUTE_PATH_ROOT = '/'
const ROUTE_PATH_LOGIN = '/login'
const ROUTE_PATH_DASHBOARD = '/dashboard'
const ROUTE_PATH_ALARM_MANAGEMENT = '/alarm-management'
const ROUTE_PATH_COMPARATIVE_ANALYSIS = '/comparative-analysis'
const ROUTE_PATH_CONSUMPTION_ANALYSIS = '/consumption-analysis'
const ROUTE_PATH_ELECTRICITY_DATA_MANAGEMENT = '/electricity-data-analysis'
const ROUTE_PATH_EQUIPMENT_MANAGEMENT = '/equipment-management'
const ROUTE_PATH_ENVIRONMENT_MANAGEMENT = '/environment-management'

export {
  ROUTE_PATH_ALARM_MANAGEMENT,
  ROUTE_PATH_COMPARATIVE_ANALYSIS,
  ROUTE_PATH_CONSUMPTION_ANALYSIS,
  ROUTE_PATH_DASHBOARD,
  ROUTE_PATH_ELECTRICITY_DATA_MANAGEMENT,
  ROUTE_PATH_ENVIRONMENT_MANAGEMENT,
  ROUTE_PATH_EQUIPMENT_MANAGEMENT,
  ROUTE_PATH_LOGIN,
  ROUTE_PATH_MATCH_ALL,
  ROUTE_PATH_ROOT
}
